// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmF9ROrNH4INaNz61k1eVV-UvtplYz6mQ',
    appId: '1:903399799969:web:b3e576c32e2928990d04e0',
    messagingSenderId: '903399799969',
    projectId: 'finalmoviles-989f3',
    authDomain: 'finalmoviles-989f3.firebaseapp.com',
    storageBucket: 'finalmoviles-989f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB24rI8MNQIhZBo13JomJM-0-T4naZfszI',
    appId: '1:903399799969:android:dfded367bfde8ace0d04e0',
    messagingSenderId: '903399799969',
    projectId: 'finalmoviles-989f3',
    storageBucket: 'finalmoviles-989f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhO6LRzXxP_991UbbeLzgqBtIZj3jrbRw',
    appId: '1:903399799969:ios:79cb9fa29d6602920d04e0',
    messagingSenderId: '903399799969',
    projectId: 'finalmoviles-989f3',
    storageBucket: 'finalmoviles-989f3.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhO6LRzXxP_991UbbeLzgqBtIZj3jrbRw',
    appId: '1:903399799969:ios:3d3206d6585857270d04e0',
    messagingSenderId: '903399799969',
    projectId: 'finalmoviles-989f3',
    storageBucket: 'finalmoviles-989f3.appspot.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
